server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: docup-backend

docup:
  upload:
    path: ${UPLOAD_PATH:./uploads}
    allowed-types: jpg,jpeg,png,pdf
    max-file-size: 10485760  # 10MB in bytes
  clamav:
    host: ${CLAMAV_HOST:localhost}
    port: ${CLAMAV_PORT:3310}
    timeout: 10000
  ocr:
    language: eng+deu
    tesseract-path: ${TESSERACT_PATH:/usr/bin/tesseract}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.docup: INFO
    com.docup.controller: DEBUG
    com.docup.service: DEBUG
    org.springframework.web.multipart: INFO
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
    org.springframework.security: INFO
    org.apache.tomcat.util.http.fileupload: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/docup-backend.log
    max-size: 100MB
    max-history: 30
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
